# LLM
model_name: gpt-4
simple_model_name: gpt-3.5-turbo-16k

# Fine-tuned llm models (optional)
fine_tuning_models:
  ft_text_categorize: Null
  ft_text_property_type: Null
  ft_text_property_extract: Null
  ft_text_synthesis_type: Null
  ft_text_synthesis_extract: Null
  ft_table_convert: Null
  ft_table_categorize: Null
  ft_table_crystal_type: Null
  ft_table_property_type: Null

# LLM Options
temperature: 0.0
verbose: False

# config - agent
reconstruct: True   # Merge paragraph for reducing tokens
input_max_toknes_synthesis: Null       # max tokens for reconstruct
input_max_token_synthesis_type: 3500   # max tokens for snthesis-type
input_max_tokens_property: 3500        # max tokens for property
